### ISSUE TITLE
JSON Parsing Error

### ISSUE THREAD

**Issue by MCTzOCK** [CraftionsMC/Analytics#1]
Error when trying to get analytics for page when one user agent is invalid.

Error Message:
``Response: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data``

Additional Information:
HTTP-Status: 500 (Internal Server Error)
HTTP-Response: 
```txt
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at /craftions-app/server/index.js:192:18
    at Array.forEach (<anonymous>)
    at /craftions-app/server/index.js:168:51
    at Layer.handle [as handle_request] (/craftions-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/craftions-app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/craftions-app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/craftions-app/node_modules/express/lib/router/layer.js:95:5)
    at /craftions-app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/craftions-app/node_modules/express/lib/router/index.js:335:12)
    at next (/craftions-app/node_modules/express/lib/router/index.js:275:10)
```

HTTP-Request-Body: ``{"host":"mctzock.de"}``

**Comment by MCTzOCK** [comment]
Fixed in 99a25d2
